
version: '3.8'
services:
  pg_db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb
    volumes:
      - pg_db:/var/lib/postgresql/data
  pdAdmin:  
    image: dpage/pgadmin4:6.17
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
volumes:
  pg_db: